// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


function removeDuplicates(nums) {
  if (nums.length <= 1) {
    return nums.length;
  } else {
    return nums.length - 1 | 0;
  }
}

console.log("Hello, BuckleScript");

exports.removeDuplicates = removeDuplicates;
/*  Not a pure module */
